language: python
python:
- 3.6
install:
- pip install pipenv
- PIPENV_IGNORE_VIRTUALENVS=1 pipenv install --dev
script:
- pipenv run pytest
after_success:
- pipenv run coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_c4008ce68f84_key -iv $encrypted_c4008ce68f84_iv
  -in realconfig.ini.enc -out threedi_scenario_downloader/tests/testdata/realconfig.ini
  -d
